version: '3'

services:

  worker:
    labels:
      shipyard.init: 'poetry run flask db upgrade'
    build: '.'
    environment:
      DATABASE_URL: 'postgres://obscure-user:obscure-password@postgres/app'
      DEV: ${DEV}
      FLASK_DEBUG: '1'
    command: '/entrypoints/worker.sh'
    volumes:
      - './filesystem/entrypoints:/entrypoints:ro'
      - './migrations:/srv/migrations'
      - './src:/srv/src:ro'

  redis:
    image: 'redis:5.0-alpine'
    ports:
      - '6379'

volumes:
  postgres:
